package sdl

// [Scancode] is a structure specifying the SDL keyboard scancode representations.
//
// [Scancode]: https://wiki.libsdl.org/SDL3/SDL_Scancode
type Scancode uint32

const (
	ScancodeUnknown            Scancode = 0
	ScancodeA                  Scancode = 4
	ScancodeB                  Scancode = 5
	ScancodeC                  Scancode = 6
	ScancodeD                  Scancode = 7
	ScancodeE                  Scancode = 8
	ScancodeF                  Scancode = 9
	ScancodeG                  Scancode = 10
	ScancodeH                  Scancode = 11
	ScancodeI                  Scancode = 12
	ScancodeJ                  Scancode = 13
	ScancodeK                  Scancode = 14
	ScancodeL                  Scancode = 15
	ScancodeM                  Scancode = 16
	ScancodeN                  Scancode = 17
	ScancodeO                  Scancode = 18
	ScancodeP                  Scancode = 19
	ScancodeQ                  Scancode = 20
	ScancodeR                  Scancode = 21
	ScancodeS                  Scancode = 22
	ScancodeT                  Scancode = 23
	ScancodeU                  Scancode = 24
	ScancodeV                  Scancode = 25
	ScancodeW                  Scancode = 26
	ScancodeX                  Scancode = 27
	ScancodeY                  Scancode = 28
	ScancodeZ                  Scancode = 29
	Scancode1                  Scancode = 30
	Scancode2                  Scancode = 31
	Scancode3                  Scancode = 32
	Scancode4                  Scancode = 33
	Scancode5                  Scancode = 34
	Scancode6                  Scancode = 35
	Scancode7                  Scancode = 36
	Scancode8                  Scancode = 37
	Scancode9                  Scancode = 38
	Scancode0                  Scancode = 39
	ScancodeReturn             Scancode = 40
	ScancodeEscape             Scancode = 41
	ScancodeBackspace          Scancode = 42
	ScancodeTab                Scancode = 43
	ScancodeSpace              Scancode = 44
	ScancodeMinus              Scancode = 45
	ScancodeEquals             Scancode = 46
	ScancodeLeftBracket        Scancode = 47
	ScancodeRightBracket       Scancode = 48
	ScancodeBackslash          Scancode = 49 // Located at the lower left of the return key on ISO keyboards and at the right end of the QWERTY row on ANSI keyboards. Produces REVERSE SOLIDUS (backslash) and VERTICAL LINE in a US layout, REVERSE SOLIDUS and VERTICAL LINE in a UK Mac layout, NUMBER SIGN and TILDE in a UK Windows layout, DOLLAR SIGN and POUND SIGN in a Swiss German layout, NUMBER SIGN and APOSTROPHE in a German layout, GRAVE ACCENT and POUND SIGN in a French Mac layout, and ASTERISK and MICRO SIGN in a French Windows layout.
	ScancodeNonUSHash          Scancode = 50 // ISO USB keyboards actually use this code instead of 49 for the same key, but all OSes I've seen treat the two codes identically. So, as an implementor, unless your keyboard generates both of those codes and your OS treats them differently, you should generate SDL_SCANCODE_BACKSLASH instead of this code. As a user, you should not rely on this code because SDL will never generate it with most (all?) keyboards.
	ScancodeSemicolon          Scancode = 51
	ScancodeApostrophe         Scancode = 52
	ScancodeGrave              Scancode = 53 // Located in the top left corner (on both ANSI and ISO keyboards). Produces GRAVE ACCENT and TILDE in a US Windows layout and in US and UK Mac layouts on ANSI keyboards, GRAVE ACCENT and NOT SIGN in a UK Windows layout, SECTION SIGN and PLUS-MINUS SIGN in US and UK Mac layouts on ISO keyboards, SECTION SIGN and DEGREE SIGN in a Swiss German layout (Mac: only on ISO keyboards), CIRCUMFLEX ACCENT and DEGREE SIGN in a German layout (Mac: only on ISO keyboards), SUPERSCRIPT TWO and TILDE in a French Windows layout, COMMERCIAL AT and NUMBER SIGN in a French Mac layout on ISO keyboards, and LESS-THAN SIGN and GREATER-THAN SIGN in a Swiss German, German, or French Mac layout on ANSI keyboards.
	ScancodeComma              Scancode = 54
	ScancodePeriod             Scancode = 55
	ScancodeSlash              Scancode = 56
	ScancodeCapsLock           Scancode = 57
	ScancodeF1                 Scancode = 58
	ScancodeF2                 Scancode = 59
	ScancodeF3                 Scancode = 60
	ScancodeF4                 Scancode = 61
	ScancodeF5                 Scancode = 62
	ScancodeF6                 Scancode = 63
	ScancodeF7                 Scancode = 64
	ScancodeF8                 Scancode = 65
	ScancodeF9                 Scancode = 66
	ScancodeF10                Scancode = 67
	ScancodeF11                Scancode = 68
	ScancodeF12                Scancode = 69
	ScancodePrintScreen        Scancode = 70
	ScancodeScrollLock         Scancode = 71
	ScancodePause              Scancode = 72
	ScancodeInsert             Scancode = 73 // Insert on PC, help on some Mac keyboards (but does send code 73, not 117).
	ScancodeHome               Scancode = 74
	ScancodePageUp             Scancode = 75
	ScancodeDelete             Scancode = 76
	ScancodeEnd                Scancode = 77
	ScancodePageDown           Scancode = 78
	ScancodeRight              Scancode = 79
	ScancodeLeft               Scancode = 80
	ScancodeDown               Scancode = 81
	ScancodeUp                 Scancode = 82
	ScancodeNumLockClear       Scancode = 83 // Num lock on PC, clear on Mac keyboards.
	ScancodeKpDivide           Scancode = 84
	ScancodeKpMultiply         Scancode = 85
	ScancodeKpMinus            Scancode = 86
	ScancodeKpPlus             Scancode = 87
	ScancodeKpEnter            Scancode = 88
	ScancodeKp1                Scancode = 89
	ScancodeKp2                Scancode = 90
	ScancodeKp3                Scancode = 91
	ScancodeKp4                Scancode = 92
	ScancodeKp5                Scancode = 93
	ScancodeKp6                Scancode = 94
	ScancodeKp7                Scancode = 95
	ScancodeKp8                Scancode = 96
	ScancodeKp9                Scancode = 97
	ScancodeKp0                Scancode = 98
	ScancodeKpPeriod           Scancode = 99
	ScancodeNonUSBackslash     Scancode = 100 // This is the additional key that ISO keyboards have over ANSI ones, located between left shift and Z. Produces GRAVE ACCENT and TILDE in a US or UK Mac layout, REVERSE SOLIDUS (backslash) and VERTICAL LINE in a US or UK Windows layout, and LESS-THAN SIGN and GREATER-THAN SIGN in a Swiss German, German, or French layout.
	ScancodeApplication        Scancode = 101 // Windows contextual menu, compose.
	ScancodePower              Scancode = 102 // The USB document says this is a status flag, not a physical key - but some Mac keyboards do have a power key.
	ScancodeKpEquals           Scancode = 103
	ScancodeF13                Scancode = 104
	ScancodeF14                Scancode = 105
	ScancodeF15                Scancode = 106
	ScancodeF16                Scancode = 107
	ScancodeF17                Scancode = 108
	ScancodeF18                Scancode = 109
	ScancodeF19                Scancode = 110
	ScancodeF20                Scancode = 111
	ScancodeF21                Scancode = 112
	ScancodeF22                Scancode = 113
	ScancodeF23                Scancode = 114
	ScancodeF24                Scancode = 115
	ScancodeExecute            Scancode = 116
	ScancodeHelp               Scancode = 117 // AL Integrated Help Center.
	ScancodeMenu               Scancode = 118 // Menu (show menu).
	ScancodeSelect             Scancode = 119
	ScancodeStop               Scancode = 120 // AC Stop.
	ScancodeAgain              Scancode = 121 // AC Redo/Repeat.
	ScancodeUndo               Scancode = 122 // AC Undo.
	ScancodeCut                Scancode = 123 // AC Cut.
	ScancodeCopy               Scancode = 124 // AC Copy.
	ScancodePaste              Scancode = 125 // AC Paste.
	ScancodeFind               Scancode = 126 // AC Find.
	ScancodeMute               Scancode = 127
	ScancodeVolumeUp           Scancode = 128
	ScancodeVolumeDown         Scancode = 129
	ScancodeKpComma            Scancode = 133
	ScancodeKpEqualsAs400      Scancode = 134
	ScancodeInternational1     Scancode = 135 // used on Asian keyboards, see footnotes in USB doc.
	ScancodeInternational2     Scancode = 136
	ScancodeInternational3     Scancode = 137 // Yen.
	ScancodeInternational4     Scancode = 138
	ScancodeInternational5     Scancode = 139
	ScancodeInternational6     Scancode = 140
	ScancodeInternational7     Scancode = 141
	ScancodeInternational8     Scancode = 142
	ScancodeInternational9     Scancode = 143
	ScancodeLang1              Scancode = 144 // Hangul/English toggle.
	ScancodeLang2              Scancode = 145 // Hanja conversion.
	ScancodeLang3              Scancode = 146 // Katakana.
	ScancodeLang4              Scancode = 147 // Hiragana.
	ScancodeLang5              Scancode = 148 // Zenkaku/Hankaku.
	ScancodeLang6              Scancode = 149 // Reserved.
	ScancodeLang7              Scancode = 150 // Reserved.
	ScancodeLang8              Scancode = 151 // Reserved.
	ScancodeLang9              Scancode = 152 // Reserved.
	ScancodeAltErase           Scancode = 153 // Erase-Eaze.
	ScancodeSysReq             Scancode = 154
	ScancodeCancel             Scancode = 155 // AC Cancel.
	ScancodeClear              Scancode = 156
	ScancodePrior              Scancode = 157
	ScancodeReturn2            Scancode = 158
	ScancodeSeparator          Scancode = 159
	ScancodeOut                Scancode = 160
	ScancodeOper               Scancode = 161
	ScancodeClearAgain         Scancode = 162
	ScancodeCrSel              Scancode = 163
	ScancodeExSel              Scancode = 164
	ScancodeKp00               Scancode = 176
	ScancodeKp000              Scancode = 177
	ScancodeThousandsSeparator Scancode = 178
	ScancodeDecimalSeparator   Scancode = 179
	ScancodeCurrencyUnit       Scancode = 180
	ScancodeCurrencySubunit    Scancode = 181
	ScancodeKpLeftParen        Scancode = 182
	ScancodeKpRightParen       Scancode = 183
	ScancodeKpLeftBrace        Scancode = 184
	ScancodeKpRightBrace       Scancode = 185
	ScancodeKpTab              Scancode = 186
	ScancodeKpBackspace        Scancode = 187
	ScancodeKpA                Scancode = 188
	ScancodeKpB                Scancode = 189
	ScancodeKpC                Scancode = 190
	ScancodeKpD                Scancode = 191
	ScancodeKpE                Scancode = 192
	ScancodeKpF                Scancode = 193
	ScancodeKpXor              Scancode = 194
	ScancodeKpPower            Scancode = 195
	ScancodeKpPercent          Scancode = 196
	ScancodeKpLess             Scancode = 197
	ScancodeKpGreater          Scancode = 198
	ScancodeKpAmpersand        Scancode = 199
	ScancodeKpDblAmpersand     Scancode = 200
	ScancodeKpVerticalBar      Scancode = 201
	ScancodeKpDblverticalBar   Scancode = 202
	ScancodeKpColon            Scancode = 203
	ScancodeKpHash             Scancode = 204
	ScancodeKpSpace            Scancode = 205
	ScancodeKpAt               Scancode = 206
	ScancodeKpExclam           Scancode = 207
	ScancodeKpMemStore         Scancode = 208
	ScancodeKpMemRecall        Scancode = 209
	ScancodeKpMemClear         Scancode = 210
	ScancodeKpMemAdd           Scancode = 211
	ScancodeKpMemSubtract      Scancode = 212
	ScancodeKpMemMultiply      Scancode = 213
	ScancodeKpMemDivide        Scancode = 214
	ScancodeKpPlusMinus        Scancode = 215
	ScancodeKpClear            Scancode = 216
	ScancodeKpClearEntry       Scancode = 217
	ScancodeKpBinary           Scancode = 218
	ScancodeKpOctal            Scancode = 219
	ScancodeKpDecimal          Scancode = 220
	ScancodeKpHexadecimal      Scancode = 221
	ScancodeLCtrl              Scancode = 224
	ScancodeLShift             Scancode = 225
	ScancodeLAlt               Scancode = 226 // Alt, option.
	ScancodeLGui               Scancode = 227 // Windows, command (apple), meta.
	ScancodeRCtrl              Scancode = 228
	ScancodeRShift             Scancode = 229
	ScancodeRAlt               Scancode = 230 // Alt gr, option.
	ScancodeRGui               Scancode = 231 // Windows, command (apple), meta.
	ScancodeMode               Scancode = 257
	ScancodeSleep              Scancode = 258 // Sleep.
	ScancodeWake               Scancode = 259 // Wake.
	ScancodeChannelIncrement   Scancode = 260 // Channel Increment.
	ScancodeChannelDecrement   Scancode = 261 // Channel Decrement.
	ScancodeMediaPlay          Scancode = 262 // Play.
	ScancodeMediaPause         Scancode = 263 // Pause.
	ScancodeMediaRecord        Scancode = 264 // Record.
	ScancodeMediaFastForward   Scancode = 265 // Fast Forward.
	ScancodeMediaRewind        Scancode = 266 // Rewind.
	ScancodeMediaNextTrack     Scancode = 267 // Next Track.
	ScancodeMediaPreviousTrack Scancode = 268 // Previous Track.
	ScancodeMediaStop          Scancode = 269 // Stop.
	ScancodeMediaEject         Scancode = 270 // Eject.
	ScancodeMediaPlayPause     Scancode = 271 // Play / Pause.
	ScancodeMediaSelect        Scancode = 272 // Media Select.
	ScancodeAcNew              Scancode = 273 // AC New.
	ScancodeAcOpen             Scancode = 274 // AC Open.
	ScancodeAcClose            Scancode = 275 // AC Close.
	ScancodeAcExit             Scancode = 276 // AC Exit.
	ScancodeAcSave             Scancode = 277 // AC Save.
	ScancodeAcPrint            Scancode = 278 // AC Print.
	ScancodeAcProperties       Scancode = 279 // AC Properties.
	ScancodeAcSearch           Scancode = 280 // AC Search.
	ScancodeAcHome             Scancode = 281 // AC Home.
	ScancodeAcBack             Scancode = 282 // AC Back.
	ScancodeAcForward          Scancode = 283 // AC Forward.
	ScancodeAcStop             Scancode = 284 // AC Stop.
	ScancodeAcRefresh          Scancode = 285 // AC Refresh.
	ScancodeAcBookmarks        Scancode = 286 // AC Bookmarks.
	ScancodeSoftLeft           Scancode = 287 // Usually situated below the display on phones and used as a multi-function feature key for selecting a software defined function shown on the bottom left of the display.
	ScancodeSoftRight          Scancode = 288 // Usually situated below the display on phones and used as a multi-function feature key for selecting a software defined function shown on the bottom right of the display.
	ScancodeCall               Scancode = 289 // Used for accepting phone calls.
	ScancodeEndCall            Scancode = 290 // Used for rejecting phone calls.
	ScancodeReserved           Scancode = 400 // 400-500 reserved for dynamic keycodes.
	ScancodeCount              Scancode = 512 // Not a key, just marks the number of scancodes for array bounds.
)
